[build]
  command = "npm install @radix-ui/react-accordion @radix-ui/react-dropdown-menu @radix-ui/react-label @radix-ui/react-select @radix-ui/react-slider @radix-ui/react-switch @radix-ui/react-tabs recharts react-day-picker && npm run build --no-lint"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_NPM = "true"
