build = "npm install && npm run build"
publish = "/opt/build/repo/.next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"
  SKIP_TYPESCRIPT_CHECK = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
