[build]
  command = "npm install && npm run build"
  publish = ".next"
  
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/*.css"
  [headers.values]
    Content-Type = "text/css"
