[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  ELEVENLABS_API_KEY = ""
  EMAIL_FROM = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
  NEXT_PUBLIC_SUPABASE_URL = ""
  OPENAI_API_KEY = ""
  S3_BUCKET_NAME = ""
  SENDGRID_API_KEY = ""
  STRIPE_MONTHLY_PRICE_ID = ""
  STRIPE_SECRET_KEY = ""
  YOUTUBE_API_KEY = ""
  YOUTUBE_AWS_ACCESS_KEY = ""
  YOUTUBE_AWS_REGION = ""
  YOUTUBE_AWS_SECRET_KEY = ""
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
